
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package XMLanalizadoxml;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CLOSING_TAG = 23;
  public static final int LT = 21;
  public static final int PYC = 13;
  public static final int PLUS = 14;
  public static final int IGUAL = 12;
  public static final int INT = 2;
  public static final int DECIMAL = 18;
  public static final int SELF_CLOSING_TAG = 24;
  public static final int GT = 22;
  public static final int CC = 8;
  public static final int ID = 16;
  public static final int CA = 7;
  public static final int NUM = 17;
  public static final int DP = 9;
  public static final int QUOTE = 26;
  public static final int PRO = 15;
  public static final int LLC = 6;
  public static final int EQUALS = 25;
  public static final int STRING = 4;
  public static final int COMMA = 10;
  public static final int LLA = 5;
  public static final int EOF = 0;
  public static final int COMILLA = 11;
  public static final int error = 1;
  public static final int XML_START = 19;
  public static final int XML_END = 20;
  public static final int DOUBLE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "STRING",
  "LLA",
  "LLC",
  "CA",
  "CC",
  "DP",
  "COMMA",
  "COMILLA",
  "IGUAL",
  "PYC",
  "PLUS",
  "PRO",
  "ID",
  "NUM",
  "DECIMAL",
  "XML_START",
  "XML_END",
  "LT",
  "GT",
  "CLOSING_TAG",
  "SELF_CLOSING_TAG",
  "EQUALS",
  "QUOTE"
  };
}

